Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity: 
  Max: 10

Metrics/LineLength:
  Max: 170

Metrics/MethodLength: 
  Max: 100

Metrics/ModuleLength:
  Enabled: false
  
Metrics/PerceivedComplexity: 
  Max: 10

Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
